namespace Nyxel.Compiler.Syntax;

public enum SyntaxKind
{
    None,

    // Special tokens.
    BadToken,
    EndOfFileToken,
    IdentifierToken,
    NumericLiteralToken,
    StringLiteralToken,
    CharacterLiteralToken,
    InterpolatedStringStartToken,
    InterpolatedStringTextToken,
    InterpolationFormatToken,
    InterpolatedStringEndToken,

    // Punctuation and operators.
    OpenBraceToken,
    CloseBraceToken,
    OpenParenToken,
    CloseParenToken,
    OpenBracketToken,
    CloseBracketToken,
    CommaToken,
    DotToken,
    QuestionDotToken,
    ColonToken,
    QuestionToken,
    QuestionQuestionToken,
    MinusGreaterThanToken,
    DotDotLessThanToken,
    DotDotDotToken,
    EqualsToken,
    EqualsEqualsToken,
    ExclamationEqualsToken,
    LessThanToken,
    LessThanEqualsToken,
    GreaterThanToken,
    GreaterThanEqualsToken,
    LessThanLessThanToken,
    PlusToken,
    MinusToken,
    AsteriskToken,
    SlashToken,
    PercentToken,
    AmpersandToken,
    BarToken,
    CaretToken,
    TildeToken,
    PlusEqualsToken,
    MinusEqualsToken,
    AsteriskEqualsToken,
    SlashEqualsToken,
    PercentEqualsToken,
    AmpersandEqualsToken,
    BarEqualsToken,
    CaretEqualsToken,
    LessThanLessThanEqualsToken,
    QuestionQuestionEqualsToken,

    // Composed by the parser from adjacent '>' tokens, so that '>>' can also close two type argument lists.
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanEqualsToken,

    // Tokens from other languages. The lexer keeps them so the parser can say what to write instead.
    AmpersandAmpersandToken,
    BarBarToken,
    ExclamationToken,
    PlusPlusToken,
    MinusMinusToken,
    EqualsGreaterThanToken,
    SemicolonToken,
    DotDotToken,

    // Keywords.
    LetKeyword,
    VarKeyword,
    FuncKeyword,
    InitKeyword,
    PropertyKeyword,
    EventKeyword,
    ClassKeyword,
    StructKeyword,
    InterfaceKeyword,
    EnumKeyword,
    CaseKeyword,
    ExtensionKeyword,
    NamespaceKeyword,
    ImportKeyword,
    PublicKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    StaticKeyword,
    VirtualKeyword,
    OverrideKeyword,
    AbstractKeyword,
    SealedKeyword,
    AsyncKeyword,
    AwaitKeyword,
    LaunchKeyword,
    EmitKeyword,
    IfKeyword,
    ElseKeyword,
    MatchKeyword,
    WhenKeyword,
    ForKeyword,
    InKeyword,
    WhileKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,
    ThrowKeyword,
    TryKeyword,
    CatchKeyword,
    FinallyKeyword,
    UsingKeyword,
    NewKeyword,
    SelfKeyword,
    SuperKeyword,
    TrueKeyword,
    FalseKeyword,
    NullKeyword,
    AndKeyword,
    OrKeyword,
    NotKeyword,
    IsKeyword,
    AsKeyword,
    OutKeyword,
    RefKeyword,

    // Built-in type keywords (ADR-0007).
    BoolKeyword,
    ByteKeyword,
    SByteKeyword,
    ShortKeyword,
    UShortKeyword,
    IntKeyword,
    UIntKeyword,
    LongKeyword,
    ULongKeyword,
    FloatKeyword,
    DoubleKeyword,
    DecimalKeyword,
    CharKeyword,
    StringKeyword,
    ObjectKeyword,

    // array<T> (ADR-0020), array2d<T> and array3d<T> (ADR-0022): type keywords, but with a type argument, so not
    // among the predefined types above.
    ArrayKeyword,
    Array2DKeyword,
    Array3DKeyword,

    // Trivia.
    WhitespaceTrivia,
    EndOfLineTrivia,
    LineCommentTrivia,
    DocCommentTrivia,
    BlockCommentTrivia,
    SkippedTokensTrivia,

    // File structure.
    CompilationUnit,
    NamespaceDeclaration,
    ImportDirective,

    // Declarations.
    ClassDeclaration,
    StructDeclaration,
    InterfaceDeclaration,
    EnumDeclaration,
    EnumCaseDeclaration,
    ExtensionDeclaration,
    FieldDeclaration,
    FunctionDeclaration,
    InitDeclaration,
    PropertyDeclaration,
    AccessorList,
    GetAccessorDeclaration,
    SetAccessorDeclaration,
    SetterParameter,
    EventDeclaration,
    BaseList,
    TypeParameterList,
    TypeParameter,
    TypeParameterConstraintClause,
    TypeConstraint,
    ClassConstraint,
    StructConstraint,
    ConstructorConstraint,
    ParameterList,
    Parameter,
    SelfParameter,
    TypeAnnotation,
    EqualsValueClause,
    ReturnTypeClause,
    ExpressionBody,

    // Types and names.
    IdentifierName,
    GenericName,
    QualifiedName,
    TypeArgumentList,
    PredefinedType,
    NullableType,
    FunctionType,
    ArrayType,
    TupleType,
    TupleElement,

    // Statements.
    Block,
    LocalDeclarationStatement,
    DeconstructionDeclarationStatement,
    Deconstruction,
    UsingDeclarationStatement,
    ExpressionStatement,
    AssignmentStatement,
    WhileStatement,
    ForStatement,
    ReturnStatement,
    ThrowStatement,
    BreakStatement,
    ContinueStatement,
    EmitStatement,

    // Expressions.
    NumericLiteralExpression,
    StringLiteralExpression,
    CharacterLiteralExpression,
    TrueLiteralExpression,
    FalseLiteralExpression,
    NullLiteralExpression,
    InterpolatedStringExpression,
    InterpolatedStringText,
    Interpolation,
    InterpolationAlignmentClause,
    InterpolationFormatClause,
    SelfExpression,
    SuperExpression,
    ParenthesizedExpression,
    TupleExpression,
    CollectionExpression,
    SimpleMemberAccessExpression,
    ConditionalMemberAccessExpression,
    InvocationExpression,
    ElementAccessExpression,
    ArgumentList,
    BracketedArgumentList,
    Argument,
    NameEquals,
    DeclarationExpression,
    ObjectCreationExpression,
    LambdaExpression,
    IfExpression,
    ElseClause,
    MatchExpression,
    MatchArm,
    WhenClause,
    TryExpression,
    CatchClause,
    FinallyClause,
    ReturnExpression,
    ThrowExpression,
    BreakExpression,
    ContinueExpression,
    UnaryMinusExpression,
    UnaryPlusExpression,
    BitwiseNotExpression,
    LogicalNotExpression,
    AwaitExpression,
    LaunchExpression,
    AsExpression,
    IsExpression,
    RangeExpression,
    MultiplyExpression,
    DivideExpression,
    ModuloExpression,
    AddExpression,
    SubtractExpression,
    LeftShiftExpression,
    RightShiftExpression,
    LessThanExpression,
    LessThanOrEqualExpression,
    GreaterThanExpression,
    GreaterThanOrEqualExpression,
    EqualsExpression,
    NotEqualsExpression,
    BitwiseAndExpression,
    ExclusiveOrExpression,
    BitwiseOrExpression,
    LogicalAndExpression,
    LogicalOrExpression,
    CoalesceExpression,

    // Patterns.
    ConstantPattern,
    RelationalPattern,
    RangePattern,
    TypePattern,
    CasePattern,
    CaseFieldList,
    NotPattern,
    AndPattern,
    OrPattern,
}
